### PR TITLE
Make PockyBot into a Library and extract deployment code

### LINKED ISSUE #115: Extract deployment code from PockyBot
Currently PockyBot deployment code is located in the git repo - deployment.yml, pr-config.yml, everything. Deployment should not be the concern of this codebase.

I would like to make PockyBot essentially a library you can pull in, and make another deployment project for the current usage of GlobalX in a private GlobalX github repository. 

This would also be the first stepping stone towards making PockyBot configurable to different messaging services.

### PR DESCRIPTION
**Pull request by Evangelinexx**
Fixes #115

### CODE REVIEW

**Comment by Evangelinexx** [comment]
Work in progress npm library [can be found here](https://www.npmjs.com/package/pockybot).

**Comment by Evangelinexx** [comment]
For those unsure of what is going on here: things inside index.ts are things that will be exported when the library is published. Everything else is internally available.

**Comment by Lauraducky** [comment]
Need to remove unused dependencies such as express

**Comment by gillianmilne** [comment]
can the dependency on google cloud be shifted out at all, have an interface that abstracts it and lets you choose?

**Comment by Evangelinexx** [comment]
> can the dependency on google cloud be shifted out at all, have an interface that abstracts it and lets you choose?

@gillianmilne this seems like a separate issue. Maybe create one?

**Comment by gillianmilne** [comment]
> > can the dependency on google cloud be shifted out at all, have an interface that abstracts it and lets you choose?
> 
> @gillianmilne this seems like a separate issue. Maybe create one?

done

**Pull request merged**
