### PR TITLE
Ignore message if PockyBot is not the first mention

### LINKED ISSUE #51: Ignore messages where PockyBot is not the first mention
So that Pockybot does not handle messages where it is mentioned incidentally, in order for a message to be valid the first thing in the message must be a mention of the bot (group messages only, PMs excluded)

### PR DESCRIPTION
**Pull request by Chromadream**
Fixes #51

### CODE REVIEW

**Comment by jimcullenaus** [comment]
Could you edit the PR description to say "Fixes #51". That's the keyword needed for auto-resolving tickets.

**Comment by jimcullenaus** [comment]
@Lauraducky get this man a PockyBot pin.

**Comment by Lauraducky** [comment]
Also need to make index and pm-index check if the responder is null before trying to create a message

**Comment by Chromadream** [comment]
> Also need to make index and pm-index check if the responder is null before trying to create a message

Yup. I completely forgot to make index check for null on responder. pm-index is unaffected though. Updated.

**Pull request merged**
