### PR TITLE
removed code block from role config help message

### LINKED ISSUE #75: Fix roleconfig help message
Currently the roleconfig help message is displayed incorrectly in a code block:
image
Not a huge deal but it should be fixed.

### PR DESCRIPTION
**Pull request by AmreenC**
this fixes #75

### CODE REVIEW

**Comment by jimcullenaus** [comment]
Does this relate to an existing ticket?

**Comment by AmreenC** [comment]
yes Jim, issue #75

**Comment by jimcullenaus** [comment]
@AmreenC please edit the description to state that this 'fixes #75'

**Comment by AmreenC** [comment]
it created new issue in progress #127

**Comment by gillianmilne** [comment]
Weird, is it just the indentation that causes it to appear as a codeblock?

**Comment by jimcullenaus** [comment]
@gillianmilne yeah it's standard markdown. Lines beginning with four spaces become codeblocks.

**Pull request merged**
